config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'

  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end

    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end
  resources :categories
  resources :users, only: [:show, :edit, :create, :update] 

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include Voteable
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  belongs_to :post
  # Move code to Concern (config.root/lib/voteable.rb) 
  #has_many :votes, as: :voteable

  validates :body, presence: true
  

# Move code to Concern (config.root/lib/voteable.rb) 
=begin
  def total_votes
    self.up_votes - self.down_votes
  end

  def up_votes
    self.votes.where(vote: true).size
  end
  
  def down_votes
    self.votes.where(vote: false).size
  end
=end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @post = Post.find_by( slug: params[:post_id])
    @comment = @post.comments.build( comment_params )
    #@comment.creator = current_user
    #@comment.creator = User.first #TODO : Fix after the authentacation
    @comment.creator = current_user
    
    if @comment.save
      flash[:notice] = "Your comment was added"
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end

  end

  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.create(voteable: @comment, creator: current_user, vote: params[:vote])
   
    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = 'Your vote was counted.'
        else
          flash[:error] = 'You can only vote on a post once.'
        end
        redirect_to :back
      end
      format.js
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end


end

app/views/comments/_comment.html.erb
<% show_post ||= false %>

<div class="row">
  <div class='span0 well text-center'>
    <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: :POST, remote: true do %>
      <i class='icon-arrow-up'></i>
    <% end %>
    <br/>
    <span id="comment_<%= comment.id%>_votes"><%= comment.total_votes %> votes</span>
    <br/>
    <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: :POST, remote: true do %>
      <i class='icon-arrow-down'></i>
    <% end %>
  </div>

  <div class= "well span8">
    <em> <%= comment.body%> </em>
    <% if show_post %>
      on <%= link_to comment.post.title, post_path(comment.post)%>
    <%end%>
    <br/>

    <span class="quite"> posted by </span> <%= link_to(comment.creator.username, user_path(comment.creator)) if comment.creator.present?%>

    <small>at <%= display_datetime(comment.created_at) %></small>

  </div>
</div>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $('#comment_<%=@comment.id%>_votes').html('<%= @comment.total_votes %> votes');
<% else %>
  alert("You can only vote on a comment once.");
<% end %>