config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'

  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end

    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end
  resources :categories
  resources :users, only: [:show, :edit, :create, :update] 

end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable

  belongs_to :creator, class_name: 'User', foreign_key: 'user_id' 
  has_many :comments

  has_many :post_categories
  has_many :categories, through: :post_categories

  # Move code to Concern (config.root/lib/voteable.rb) 
  #has_many :votes, as: :voteable


  validates :title, presence: true, length: {minimum: 5}
  validates :description, presence: true
  validates :url, presence: true, uniqueness: true

  sluggable_column :title

  # Move code to Concern (config.root/lib/sluggable.rb) 
  #before_save :generate_slug!

# Move code to Concern (config.root/lib/voteable.rb) 
=begin
  def total_votes
    self.up_votes - self.down_votes
  end

  def up_votes
    self.votes.where(vote: true).size
  end
  
  def down_votes
    self.votes.where(vote: false).size
  end
=end

# Move code to Concern (config.root/lib/sluggable.rb) 
=begin

  def to_param
    self.slug
  end

  def generate_slug!
    the_slug = to_slug(self.title)
    post = Post.find_by slug: the_slug
    count = 2
    while post && post != self
      the_slug = append_suffix(the_slug, count)
      post = Post.find_by slug: the_slug
      count += 1
    end
    self.slug = the_slug
  end

  def append_suffix(str, count)
    if str.split('-').last.to_i != 0
      return str.split('-').slice(0...-1).join('-') + '-' + count.to_s
    else
      return str + '-' + count.to_s
    end
  end

  def to_slug(title)
    str = title.strip
    str.gsub! /\s*[^A-Za-z0-9]\s*/, '-'
    str.gsub! /-+/, "-"
    str.downcase
  end
=end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:vote, :show, :edit, :update, :destroy]
  before_action :require_user, except:[:index, :show]
  before_action :require_creator, only: [:edit, :update]

  def index
    @posts = Post.all.sort_by{|x| x.total_votes}.reverse
    #expires_in 999999999999, piblic: true
    fresh_when @products, public: true
  end
  
  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    #@post.creator = User.first #TODO: change once we have authentication
    @post.creator = current_user
    if @post.save 
      flash[:notice] = 'You post was created'
      redirect_to posts_path
    else
      render :new
    end

  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "The post was updated"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
  end

  def vote

    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])
    
    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = 'Your vote was counted.'
        else
          flash[:error] = 'You can only vote on a post once.'
        end
        redirect_to :back
      end
      # Add fotmat.js to handle request from js(ajax)
      format.js
    end
  end

  
  private
  def set_post
    @post = Post.find_by(slug: params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def require_creator
    access_denied unless logged_in? and (current_user == @post.creator || current_user.admin?)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<!--
<%# if @post.errors.any? %>
  <div class= "alert alert-error">
    <h5>There were some errors: </h5>
    <ul>
      <%# @post.errors.full_messages.each do |msg|%>
      <li> <%#= msg%> </li>
      <%# end %>
    </ul>
  </div>
<%#end%>
-->

<%= render partial: 'shared/errors', locals: {obj: @post} %>

<div class="well">
  <%= form_for @post do |f|%>
    <div class="control-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="control-group">
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>

    <div class="control-group">
      <%= f.label :description %>
      <%= f.text_field :description, rows: 6 %>
    </div>

    <div class="control-group">
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb|%>
      <%  cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
      <% end %>
    </div>

    <%= f.submit(@post.new_record? ? "Create Post" : "Update Post", class: 'btn btn-primary') %>

  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="row">

<%# binding.pry%>
  <div class='span0 well text-center'>
    <%= link_to vote_post_path(post, vote: true), method: :POST, remote: true do%>
      <i class='icon-arrow-up'></i>
    <%end%>
    <br/>
    <span id="post_<%= post.slug%>_votes"><%= post.total_votes %> votes</span>
    <br/>

    <%= link_to vote_post_path(post, vote: false), method: :POST, remote: true do %>
      <i class='icon-arrow-down'></i>
    <% end %>
  </div>

  <div class="span8 well">
    <%= render post.categories%>
    <h4><%=link_to post.title, fix_url(post.url) %></h4>
    <p><%= post.description %></p>
    <p> 
      <span class="quite">posted by</span> <%= link_to(post.creator.username, user_path(post.creator) ) if post.creator.present?%>
      <small>at <%= display_datetime(post.created_at) %></small>
    </p>
      <small>
        <span>
          <%= link_to("#{post.comments.size} commnet", post_path(post) )%>
        </span>
      </small>
    
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit the post' %>

<%= render 'form' %>

app/views/posts/index.html.erb
<p class='lead'>
  All Post
  <hr/>
</p>

<% @posts.each do |post| %>
  <%= render partial: 'post', locals: {post: post}%>
<% end %>

app/views/posts/new.html.erb
<h2> New Post </h2>

<%= render partial: 'shared/content_title', locals: {title: 'Create a new post'}%>

<%= render 'form' %>

app/views/posts/show.html.erb
<%if logged_in? %>
  <p class="pull-right">
    [<%= link_to 'edit this post', edit_post_path(@post) %>]
  </p>
<%end%>



<%= render @post.categories %>
<%#= render partial: 'categories/category', collection: @post.categories ,as: :category%>

<%= render partial: 'shared/content_title', locals: {title: @post.title}%>

<p>
  <%= @post.description%>
</p>
<hr/>

<% if logged_in? %>
  <%= form_for [@post, @comment] do |f| %>
    <%= render 'shared/errors', obj: @comment %>
    <div class="control-group">
      <%= f.label :body, 'Leave a comment'%>
      <%= f.text_area :body, rows: 4, class: 'span4'%>
    </div>
    <%= f.submit 'create comment', class: 'btn btn-primary'%>
  <% end %>
<%end%>

<h5> Comments: </h5>

<% @post.reload.comments.each do |comment| %>
  <%= render 'comments/comment', comment: comment, show_post: false%>
<%end%>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $("#post_<%= @post.slug %>_votes").html("<%= @post.total_votes%> votes")
<% else %>
  alert("You can only vote a post once.")
<% end %>