config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'

  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end

    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end
  resources :categories
  resources :users, only: [:show, :edit, :create, :update] 

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true

  before_save :generate_slug!

  def to_param
    self.slug
  end

  def generate_slug!
    the_slug = to_slug(self.name)
    category = Category.find_by slug: the_slug
    count = 2
    while category && category != self
      the_slug = append_suffix(the_slug, count)
      category = Category.find_by slug: the_slug
      count += 1
    end
    self.slug = the_slug
  end

  def append_suffix(str, count)
    if str.split('-').last.to_i != 0
      return str.split('-').slice(0...-1).join('-') + '-' + count.to_s
    else
      return str + '-' + count.to_s
    end
  end

  def to_slug(title)
    str = title.strip
    str.gsub! /\s*[^A-Za-z0-9]\s*/, '-'
    str.gsub! /-+/, "-"
    str.downcase
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_admin, only: [:new, :create]

  def index
    @category = Category.all
  end

  def show; end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was created"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "Category was updated"
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
  end

  private

  def set_category
    @category = Category.find_by( slug: params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

end

app/views/categories/_category.html.erb
<span class="badge"> <%= link_to category.name, category_path(category)%> </span>

app/views/categories/_form.html.erb
<%= render partial: 'shared/errors', locals: {obj: @category} %>

<%= form_for @category do |f| %>
  <div class= "control-group">
    <%= f.label :name%>
    <%= f.text_field :name%>
  </div>

  <%= f.submit @category.new_record? ? "create category" : "update category", class: 'btn btn-success'%>
<% end %>

app/views/categories/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Category'%>

<%= render 'form'%>

app/views/categories/index.html.erb
<%= render 'shared/content_title', title: 'All Categories'%>

<ul>
  <% @categories.each do |category| %>
    <li> <%= category.name%> </li>
  <%end%>
</ul>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: 'New Category'%>

<%= render 'form'%>

app/views/categories/show.html.erb
<% header = link_to("All Posts", posts_path) + " &raquo; #{@category.name}".html_safe %>
<%= render 'shared/content_title' , title: header%>

<%# @category.posts.each do |post| %>
  <%# render 'posts/post', post: post%>
<%#end%>


<%#= render @category.posts%>
<%= render partial: 'posts/post', collection: @category.posts, as: :post%>